services:
  webserver:
    image: "piegarden/strengthgadget:${CIRCLE_WORKFLOW_ID}"
    depends_on:
      - keydb
    environment:
      TF_VAR_cloudflare_origin_cert: "${TF_VAR_cloudflare_origin_cert}"
      TF_VAR_cloudflare_origin_cert_key: "${TF_VAR_cloudflare_origin_cert_key}"
      TF_VAR_environment: "${TF_VAR_environment}"
      TF_VAR_registration_email_from: "${TF_VAR_registration_email_from}"
      TF_VAR_registration_email_from_password: "${TF_VAR_registration_email_from_password}"
      TF_VAR_database_connection_string: "${TF_VAR_database_connection_string}"
      TF_VAR_redis_connection_string: "${TF_VAR_redis_connection_string}"
      TF_VAR_version: "${CIRCLE_WORKFLOW_ID}"
      TF_VAR_database_root_ca: "${TF_VAR_database_root_ca}"
      TF_VAR_email_root_ca: "${TF_VAR_email_root_ca}"
      TF_VAR_trusted_ui_origin: "${TF_VAR_trusted_ui_origin}"
      TF_VAR_redis_password: "${TF_VAR_redis_password}"
      TF_VAR_verification_excessive_retry_attempt_lockout_duration_in_seconds: "${TF_VAR_verification_excessive_retry_attempt_lockout_duration_in_seconds}"
      TF_VAR_allowed_verification_attempts_with_the_excessive_retry_lockout_window: "${TF_VAR_allowed_verification_attempts_with_the_excessive_retry_lockout_window}"
      TF_VAR_verification_code_validity_window_in_min: "${TF_VAR_verification_code_validity_window_in_min}"
      TF_VAR_window_length_in_seconds_for_the_number_of_allowed_verification_emails_before_lockout: "${TF_VAR_window_length_in_seconds_for_the_number_of_allowed_verification_emails_before_lockout}"
      TF_VAR_window_length_in_seconds_for_the_number_of_allowed_login_attempts_before_lockout: "${TF_VAR_window_length_in_seconds_for_the_number_of_allowed_login_attempts_before_lockout}"
      TF_VAR_allowed_login_attempts_before_triggering_lockout: "${TF_VAR_allowed_login_attempts_before_triggering_lockout}"
      TF_VAR_redis_user_private_key: "${TF_VAR_redis_user_private_key}"
      TF_VAR_redis_user_crt: "${TF_VAR_redis_user_crt}"
      TF_VAR_redis_ca: "${TF_VAR_redis_ca}"
      TF_VAR_sentry_end_point: "${TF_VAR_sentry_end_point}"
      TF_VAR_allowed_verification_resend_code_attempts_within_one_hour: "${TF_VAR_allowed_verification_resend_code_attempts_within_one_hour}"
    ports:
      - "${TF_VAR_server_port}:443"
    restart: always
    networks:
      - default
      - shared
  keydb: 
    image: "eqalpha/keydb"
    volumes:
      - "./keydb.conf:/etc/keydb/keydb.conf"
    restart: always
    networks:
      - default

networks:
  default:
  shared:
    external: true
