apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  replicas: 1  # Number of replicas you want to create
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: localhost:5000/haproxy:0.0.1
          ports:
            - containerPort: 8080  # Expose port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort
