apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: default
data:
  haproxy.cfg: |
    defaults
      log global
      mode tcp
      option tcplog
      timeout connect 5s
      timeout client 30s
      timeout server 30s

    frontend database_frontend
      bind *:26257
      default_backend database_backend

    backend database_backend
      server db1 cockroachdb-public:26257 check
