version: '3'
services:
  webserver:
    image: "piegarden/strengthgadget:${CIRCLE_WORKFLOW_ID}"
    environment:
      CERT_PEM: "${TF_VAR_cloudflare_origin_cert}"
      KEY_PEM: "${TF_VAR_cloudflare_origin_cert_key}"
      ENVIRONMENT: "${TF_VAR_environment}"
      REGISTRATION_EMAIL_FROM: "${TF_VAR_registration_email_from}"
      REGISTRATION_EMAIL_FROM_PASSWORD: "${TF_VAR_registration_email_from_password}"
      DATABASE_CONNECTION_STRING: "${TF_VAR_database_connection_string}"
      REDIS_CONNECTION_STRING: "${TF_VAR_redis_connection_string}"
      VERSION: "${CIRCLE_WORKFLOW_ID}"
      DATABASE_ROOT_CA: "${TF_VAR_database_root_ca}"
      EMAIL_ROOT_CA: "${TF_VAR_email_root_ca}"
      TRUSTED_UI_ORIGIN: "https://${TF_VAR_domain_name}"
      REDIS_PASSWORD: "${TF_VAR_redis_password}"
      VERIFICATION_EXCESSIVE_RETRY_ATTEMPT_LOCKOUT_DURATION_IN_SECONDS: "${TF_VAR_verification_excessive_retry_attempt_lockout_duration_in_seconds}"
      ALLOWED_VERIFICATION_ATTEMPTS_WITH_THE_EXCESSIVE_RETRY_LOCKOUT_WINDOW: "${TF_VAR_allowed_verification_attempts_with_the_excessive_retry_lockout_window}"
      VERIFICATION_CODE_VALIDITY_WINDOW_IN_MIN: "${TF_VAR_verification_code_validity_window_in_min}"
      WINDOW_LENGTH_IN_SECONDS_FOR_THE_NUMBER_OF_ALLOWED_VERIFICATION_EMAILS_BEFORE_LOCKOUT: "${TF_VAR_window_length_in_seconds_for_the_number_of_allowed_verification_emails_before_lockout}"
      WINDOW_LENGTH_IN_SECONDS_FOR_THE_NUMBER_OF_ALLOWED_LOGIN_ATTEMPTS_BEFORE_LOCKOUT: "${TF_VAR_window_length_in_seconds_for_the_number_of_allowed_login_attempts_before_lockout}"
      ALLOWED_LOGIN_ATTEMPTS_BEFORE_TRIGGERING_LOCKOUT: "${TF_VAR_allowed_login_attempts_before_triggering_lockout}"
      REDIS_USER_PRIVATE_KEY: "${TF_VAR_redis_user_private_key}"
      REDIS_USER_CRT: "${TF_VAR_redis_user_crt}"
      REDIS_CA_PEM_PART_ONE: "${TF_VAR_redis_ca_pem_part_one}"
      REDIS_CA_PEM_PART_TWO: "${TF_VAR_redis_ca_pem_part_two}"
      REDIS_CA_PEM_PART_THREE: "${TF_VAR_redis_ca_pem_part_three}"
      REDIS_CA_PEM_PART_FOUR: "${TF_VAR_redis_ca_pem_part_four}"
      SENTRY_END_POINT: "${TF_VAR_sentry_end_point}"
    ports:
      - "443:443"
    network_mode: host
    restart: always
