apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public-np
spec:
  type: NodePort
  selector:
    "app.kubernetes.io/component": database
    "app.kubernetes.io/instance": cockroachdb
    "app.kubernetes.io/name": cockroachdb
    crdb: is-cool
  ports:
    - protocol: TCP
      port: 26257
      targetPort: 26257  # Replace with the actual port your application uses
      nodePort: 30006
