# Reset Cluster: kind delete cluster || true && kind create cluster --config kind/kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000 # home.frii.day
        hostPort: 30000
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 30001 # watchdog.frii.day
        hostPort: 30001
      - containerPort: 30002 # icinga.frii.day
        hostPort: 30002
      - containerPort: 30003 # watchdog DB
        hostPort: 30003
      - containerPort: 30004 # watchdog redis DB
        hostPort: 30004
      - containerPort: 30005 # strengthgadget.frii.day
        hostPort: 30005
      - containerPort: 30006 # strengthgadget DB
        hostPort: 30006
      - containerPort: 30007 # strengthgadget Redis
        hostPort: 30007
      - containerPort: 30008 # watchdog-agent
        hostPort: 30008
      - containerPort: 30009 # Haproxy
        hostPort: 30009
      - containerPort: 30010 # operator postgres DB
        hostPort: 30010
      - containerPort: 30011 # Vault (operator postgres configured)
        hostPort: 30011
      - containerPort: 30012 # Vault Database
        hostPort: 30012
      - containerPort: 30013 # Watchdog Debug
        hostPort: 30013
