version: "3.9"

services:
  jenkins:
    # https://hub.docker.com/r/jenkins/jenkins
    image: localhost:5000/jenkins/jenkins:lts
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  proxy:
    image: cloudflare/cloudflared:latest
    restart: always
    network_mode: host
    command:
      - tunnel
#      - "--no-autoupdate"
#      - "--loglevel"
#      - debug
      - run
      - "--token"
      - "eyJhIjoiZDljODJhZDFhZGY5OTQ1Mjg5MDM3NGE2YmY1YTg3OWEiLCJ0IjoiMDc4Y2EyNTItZTU4ZC00ZWM2LTgyYmUtNDYzMzdlYTkyNGM3IiwicyI6Ik16TXpZelV3TmpndFpUQTFOQzAwTXpWa0xXSmpNek10TnpnMk9ETTRObVU1TnpOaiJ9"
volumes:
  jenkins_home:
