version: 2.1

jobs:
  backend-build:
    docker:
      - image: cimg/base:current
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            cd ./backend && ./deploy.sh
  backend-deploy:
    docker:
      - image: piegarden/file_mover:8.2
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Deploy new version
          command: |
            echo "$TF_VAR_backend_deployment_ssh_private_key" | base64 -d > .key && chmod 600 .key
            echo "$TF_VAR_backend_deployment_ssh_public_known_host" | base64 -d > ~/.ssh/known_hosts
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'mkdir -p strengthgadget'
            scp -i ./.key backend/docker-compose.yaml "piegarden@$TF_VAR_backend_public_ip:strengthgadget"
            printenv > .env
            scp -i ./.key .env "piegarden@$TF_VAR_backend_public_ip:strengthgadget"
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'cd strengthgadget && source ./.env && sudo docker compose restart'
  infra:
    docker:
      - image: alpine/terragrunt
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: cd ./infrastructure/terraform/live/staging/ecs && ../deploy.sh
  frontend-build:
    docker:
      - image: piegarden/strengthgadget-frontend-agent:0.0.1
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            cd ./ui && ./deploy.sh && cd ../ &&
            cd ./infrastructure/terraform/live/staging/cloudfront && ../deploy.sh
  statuscake:
    docker:
      - image: alpine/terragrunt
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: cd ./infrastructure/terraform/live/staging/statuscake && ../deploy.sh



workflows:
  deploy:
    jobs:
#      - backend-build:
#          context:
#            - context-staging
#            - context-docker-hub
#      - infra:
#          context:
#            - context-staging
#            - context-docker-hub
#      - frontend-build:
#          context:
#            - context-staging
#            - context-docker-hub
#      - statuscake:
#          context:
#            - context-staging
      - backend-deploy:
          context:
            - context-staging



