version: 2.1

jobs:
  reverse-proxy:
    docker:
      - image: piegarden/file_mover:8.2
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy reverse proxy
          command: |
            echo "$TF_VAR_backend_deployment_ssh_private_key" | base64 -d > .key && chmod 600 .key
            echo "$TF_VAR_backend_deployment_ssh_public_known_host" | base64 -d > ~/.ssh/known_hosts
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'mkdir -p reverse-proxy'
            scp -i ./.key reverse-proxy/docker-compose.yaml reverse-proxy/nginx.conf "piegarden@$TF_VAR_backend_public_ip:reverse-proxy"
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'cd reverse-proxy && sudo docker compose down || true && sudo docker compose up -d'
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    resource_class: arm.medium  # Specify ARM resource class
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            ./deploy.sh
  deploy:
    docker:
      - image: piegarden/file_mover:8.2
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy new version
          command: |
            echo "$TF_VAR_backend_deployment_ssh_private_key" | base64 -d > .key && chmod 600 .key
            echo "$TF_VAR_backend_deployment_ssh_public_known_host" | base64 -d > ~/.ssh/known_hosts
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'mkdir -p $TF_VAR_domain_name'
            scp -i ./.key docker-compose.yaml "piegarden@$TF_VAR_backend_public_ip:$TF_VAR_domain_name"
            printenv > .env
            scp -i ./.key .env "piegarden@$TF_VAR_backend_public_ip:$TF_VAR_domain_name"
            ssh -i ./.key "piegarden@$TF_VAR_backend_public_ip" 'cd $TF_VAR_domain_name && sudo docker compose down || true && sudo docker compose up -d'
  infra:
    docker:
      - image: alpine/terragrunt
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: cd ./infrastructure/terraform/live/staging/raspberry_pi && ../deploy.sh
  statuscake:
    docker:
      - image: alpine/terragrunt
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: cd ./infrastructure/terraform/live/staging/statuscake && ../deploy.sh



workflows:
  deploy:
    jobs:
      - reverse-proxy:
          filters:
            branches:
              only: master
          context:
            - context-production
            - context-docker-hub
      - build:
          name: "build production"
          filters:
            branches:
              only: master
          context:
            - context-production
            - context-docker-hub
      - infra:
          name: "infra production"
          filters:
            branches:
              only: master
          context:
            - context-production
            - context-docker-hub
      - statuscake:
          name: "statuscake production"
          filters:
            branches:
              only: master
          context:
            - context-production
      - deploy:
          name: "deploy production"
          filters:
            branches:
              only: master
          context:
            - context-production
          requires:
            - build
      - build:
          name: "build staging"
          filters:
            branches:
              only: staging
          context:
            - context-staging
            - context-docker-hub
      - infra:
          name: "infra staging"
          filters:
            branches:
              only: staging
          context:
            - context-staging
            - context-docker-hub
      - statuscake:
          name: "statuscake staging"
          filters:
            branches:
              only: staging
          context:
            - context-staging
      - deploy:
          name: "deploy staging"
          filters:
            branches:
              only: staging
          context:
            - context-staging
          requires:
            - build



