version: 2.1

jobs:
  backend-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: cd ./backend/strengthgadget && ./deploy.sh
  infra:
    docker:
      - image: alpine/terragrunt
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: cd ./infrastructure/terraform/live/staging/ecs && ../deploy.sh
  frontend-build:
    docker:
      - image: piegarden/strengthgadget-frontend-agent:0.0.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            cd ./ui && ./deploy.sh && cd ../ &&
            cd ./infrastructure/terraform/live/staging/cloudfront && ../deploy.sh


workflows:
  deploy:
    jobs:
      - backend-build:
          context:
            - strengthgadget-staging
            - docker-hub-creds
      - infra:
          context:
            - strengthgadget-staging
            - docker-hub-creds
      - frontend-build:
          context: strengthgadget-staging



