version: 2.1

jobs:
  backend-build:
    docker:
      - image: cimg/base:current
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            cd ./backend/strengthgadget && 
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin &&
            docker buildx create --use &&
            docker buildx build --platform linux/arm64 --push -t "$DOCKER_USER/strengthgadget:$CIRCLE_WORKFLOW_ID" .

  infra:
    docker:
      - image: alpine/terragrunt
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: cd ./infrastructure/terraform/live/staging/ecs && ../deploy.sh
  frontend-build:
    docker:
      - image: piegarden/strengthgadget-frontend-agent:0.0.1
        auth:
          username: $TF_VAR_docker_user
          password: $TF_VAR_docker_token
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            cd ./ui && ./deploy.sh && cd ../ &&
            cd ./infrastructure/terraform/live/staging/cloudfront && ../deploy.sh


workflows:
  deploy:
    jobs:
      - backend-build:
          context:
            - context-staging
            - context-docker-hub
      - infra:
          context:
            - context-staging
            - context-docker-hub
      - frontend-build:
          context:
            - context-staging
            - context-docker-hub



