services:
  haproxy:
    image: "haproxy:latest"
    ports: 
      - "443:443"
      - "22:22"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    restart: always
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - default
      - shared

networks:
  default:
  shared:
    external: true
    name: shared
