services:
  haproxy:
    image: "haproxy:latest"
    network_mode: "host"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    restart: always
    cap_add:
      - NET_BIND_SERVICE
