export const exercise = "/exercise"
export const login = "/login"
export const forgotPasswordEmail = "/forgotPassword/email"
export const forgotPasswordResetCode = "/forgotPassword/resetCode"
export const forgotPasswordNewPassword = "/forgotPassword/newPassword"
export const register = "/register"
export const verification = "/verification"
export const home = "/"